Repository XENONnT/straxen, pull requests merged in 2021-05, with the labels that each got.

#466 Reduce Pep8 gitHub bot verbosity
  setup.cfg
  straxen/misc.py
Labels: Testing

#459 Added support of dill for resource files
  straxen/common.py
Labels: enhancement, good first issue

#467 Added exceptions to review do
  setup.cfg
Labels: Testing

#468 Remove zero gain hits
  straxen/plugins/veto_hitlets.py
  tests/test_veto_hitlets.py
Labels: enhancement

#449 Time widget misc2
  setup.py
  straxen/misc.py
  tests/test_misc.py
Labels: enhancement

#392 Added changes for user credentials
  docs/source/setup.rst
  straxen/scada.py
  tests/test_scada.py
Labels: enhancement

#464 Update classifiers for pipy
  setup.py
Labels: documentation, good first issue

#473 Fixed difference between datetime and date
  straxen/misc.py
Labels: good first issue

#483 fix _find for rucio to include transferred. Set kwarg defaults
  straxen/rundb.py
Labels: bug, enhancement

#480 set event_info_double as endpoint for kr
  bin/bootstrax
Labels: enhancement, good first issue

#481 Documentation and package maintainance
  README.md
  bin/straxer
  docs/pull_request_template.md
  docs/source/bootstrax.rst
  docs/source/figures/online_monitor.svg
  docs/source/index.rst
  docs/source/online_monitor.rst
  docs/source/scripts.rst
  notebooks/experimental/check_raw_records.ipynb
  notebooks/experimental/compress_benchmark.ipynb
Labels: documentation

#484 use_per_run_defaults explicitly for 1T
  straxen/contexts.py
Labels: enhancement

#465 Veto plugins
  straxen/plugins/__init__.py
  straxen/plugins/nveto_recorder.py
  straxen/plugins/veto_events.py
  straxen/plugins/veto_veto_regions.py
  tests/test_nveto_events.py
  tests/test_nveto_recorder.py
  tests/test_veto_veto_regions.py
Labels: enhancement

#477 Fix AFT close but not quite 1
  setup.cfg
  straxen/plugins/peak_processing.py
  tests/test_peaks.py
Labels: bug, enhancement, good first issue, testing

#296 Veto Proximity Plugin
  straxen/plugins/acqmon_processing.py
Labels: enhancement

#494 Allow variable event duration
  straxen/contexts.py
  straxen/plugins/event_processing.py
Labels: enhancement

#501 Patch remap cabled
  straxen/common.py
Labels: bug, good first issue
