Repository XENONnT/straxen, pull requests merged in 2021-06, with the labels that each got.

#502 Bin updates
  bin/ajax
  bin/bootstrax
Labels: enhancement

#471 Itp map patch
  straxen/itp_map.py
Labels: enhancement, good first issue

#457 Standardize CMT options as (correction, version, nT=boolean)
  straxen/analyses/posrec_comparison.py
  straxen/contexts.py
  straxen/corrections_services.py
  straxen/get_corrections.py
  straxen/mini_analysis.py
  straxen/plugins/event_processing.py
  straxen/plugins/peaklet_processing.py
  straxen/plugins/position_reconstruction.py
  straxen/plugins/pulse_processing.py
  straxen/plugins/veto_hitlets.py
  tests/test_cmt.py
  tests/test_plugins.py
Labels: enhancement

#499 S1/S2 event patternfit and S1 AFT test
  straxen/contexts.py
  straxen/itp_map.py
  straxen/plugins/__init__.py
  straxen/plugins/event_area_per_channel.py
  straxen/plugins/event_patternfit.py
  tests/test_plugins.py
Labels: enhancement

#472 Add rucio frontend
  straxen/__init__.py
  straxen/contexts.py
  straxen/rucio.py
  straxen/rundb.py
  tests/test_contexts.py
  tests/test_mongo_interactions.py
  tests/test_plugins.py
Labels: enhancement

#531 Add apply_cmt_version function and xenonnt context
  docs/source/cmt.rst
  docs/source/index.rst
  straxen/analyses/posrec_comparison.py
  straxen/contexts.py
  straxen/corrections_services.py
  straxen/get_corrections.py
  straxen/misc.py
  straxen/rucio.py
  tests/test_cmt.py
  tests/test_contexts.py
Labels: enhancement

#558 Fix missing info in bootstrax docs, fix #546
  bin/bootstrax
Labels: bug

#557 Remove travis for testing from straxen
  .github/workflows/pypi_install.yml
  .travis.yml
  README.md
Labels: testing

#548 Rewrite merge s2
  straxen/plugins/peaklet_processing.py
  tests/test_several.py
  tests/test_strax_time_selection.py
Labels: enhancement

#566 debug merged S2s #548
  HISTORY.md
  straxen/plugins/peaklet_processing.py
Labels: bug

#567 disabe rucio frontend
  straxen/contexts.py
Labels: bug
