Repository XENONnT/straxen, pull requests merged in 2021-08, with the labels that each got.

#621 Stop testing py3.6
  .github/workflows/code_style.yml
  .github/workflows/contexts.yml
  .github/workflows/coveralls.yml
  .github/workflows/pypi_install.yml
  .github/workflows/pytest.yml
  docs/source/setup.rst
  extra_requirements/requirements-tests.txt
  requirements.txt
  setup.py
  straxen/misc.py
Labels: dependencies, testing

#638 pass on mappable
  straxen/matplotlib_utils.py
Labels: enhancement

#637 new plot_pmts
  straxen/matplotlib_utils.py
Labels: enhancement

#639 Pass on kwargs to rucio saver
  bin/bootstrax
  straxen/rucio.py
Labels: bug
