Repository XENONnT/straxen, pull requests merged in 2021-12, with the labels that each got.

#781 URLConfig not in strax
  extra_requirements/requirements-tests.txt
  requirements.txt
  straxen/__init__.py
  straxen/mongo_storage.py
  straxen/rundb.py
  straxen/url_config.py
  tests/test_mongo_interactions.py
  tests/test_url_config.py
Labels: bug

#813 Itp test
  tests/test_itp_map.py
Labels: testing

#828 Unittest for DAQreader
  .gitignore
  straxen/plugins/daqreader.py
  tests/test_daq_reader.py
Labels: documentation, testing

#821 use URL configs for NeuralNets
  straxen/plugins/position_reconstruction.py
  straxen/test_utils.py
  straxen/url_config.py
  tests/test_plugins.py
  tests/test_posrec_plugins.py
Labels: enhancement

#862 Pin documentation requirements
  extra_requirements/requirements-docs.txt
Labels: documentation, testing, dependencies, github_actions

#860 Add cmt tests and fix bug in apply_cmt_version
  straxen/contexts.py
  straxen/corrections_services.py
  straxen/get_corrections.py
  tests/test_cmt.py
  tests/test_contexts.py
Labels: bug, enhancement, testing, python

#856 Tests for `common.py` fix #741
  straxen/common.py
  tests/test_common.py
Labels: documentation, testing

#851 Add `strax.Context` documentation, fix #439
  docs/source/build_context_doc.py
  docs/source/conf.py
  docs/source/index.rst
  docs/source/reference/context.rst
  docs/source/reference/straxen.plugins.rst
  docs/source/reference/straxen.rst
  straxen/contexts.py
Labels: documentation

#857 Test for bokeh_utils
  tests/test_mini_analyses.py
Labels: documentation, testing

#858 Test for rucio-documents in the rundb
  tests/test_database_frontends.py
Labels: documentation, testing

#859 Test for Mongo-down/uploader
  straxen/mongo_storage.py
  tests/test_mongo_downloader.py
Labels: documentation, testing
