Repository XENONnT/straxen, pull requests merged in 2022-01, with the labels that each got.

#876 Bump numpy
  .github/workflows/test_install.yml
  extra_requirements/requirements-tests.txt
  requirements.txt
Labels: dependencies, python

#855 Tests for WFSim contexts
  straxen/contexts.py
  tests/test_contexts.py
Labels: documentation, testing

#878 test with py3.10
  .github/scripts/filter_strax_from_requirements.sh
  .github/workflows/pypi_install.yml
  .github/workflows/pytest.yml
  extra_requirements/requirements-tests.txt
  setup.py
  straxen/plugins/x1t_cuts.py
  tests/test_mini_analyses.py
Labels: testing, dependencies, python

#884 Run coveralls on remote forks
  .github/workflows/contexts.yml
  .github/workflows/pytest.yml
Labels: testing, github_actions

#863 URLConfig documentation
  docs/source/url_configs.rst
Labels: documentation
